[package]
name = "nux"
description = "Reliable UDP protocol"
repository = "https://github.com/jprochazk/nux"
license = "MIT OR Apache-2.0"
version = "0.0.0"
authors = ["jprochazk"]
edition = "2021"
readme = "README.md"

[dependencies]
